# Generated by Django 2.1 on 2020-06-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolatebar',
            name='bean_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chocolatebar',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
