# Generated by Django 2.1 on 2019-05-15 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_weight', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('calories_in', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('calories_out', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_duration', models.DurationField()),
                ('heart_rate', models.IntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('height', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('age', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('gender', models.CharField(max_length=25)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_awake', models.TimeField(blank=True)),
                ('time_slept', models.TimeField(blank=True)),
                ('sleep_duration', models.DurationField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.Entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.Setup'),
        ),
        migrations.AddField(
            model_name='calorie',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.Entry'),
        ),
    ]
