# Generated by Django 2.1 on 2019-05-16 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleep',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='date_for',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='time_awake',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='time_slept',
            field=models.DateTimeField(blank=True),
        ),
    ]
