# Generated by Django 2.1 on 2019-05-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie',
            name='calories_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='calorie',
            name='calories_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='calorie',
            name='entry_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='setup',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='setup',
            name='height',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='setup',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
