# Generated by Django 2.1 on 2019-05-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0004_auto_20190522_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='setup',
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calorie.UserProfileInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calorie.UserProfileInfo'),
            preserve_default=False,
        ),
    ]
